### ISSUE TITLE
Exclude Weblinks

### ISSUE THREAD

**Issue by pyrographics** [splittingred/GoogleSiteMap#12]
Thank you for this great snippet and your many others!  Our site has many weblinks that redirect to external resources.  This causes Google to throw errors on the sitemap.  A feature that enables exclusion of weblinks would be very useful.

**Comment by splittingred** [comment]
This can be done with the upcoming 1.3.0 release that allows:

<pre>&where=`{"class_key:!=":"modWebLink"}`</pre>
