### ISSUE TITLE
Make priority and change frequency parameters

### ISSUE THREAD

**Issue by charliez** [splittingred/GoogleSiteMap#2]
Make priority and change frequency ($update in the snippet) parameters.
This would allow this two values to be overridden per page from the ones
calculated by the snippet itself.

**Comment by charliez** [comment]
Please erase this request or issue.
I can override using the content and items Tpl's...
Sorry!

**Comment by enigmatic-user** [comment]
Well, this could be done in the Template, that's correct, but nevertheless it wouldn't be bad to have an opportunity to influence at least the priority directly. I could think of passing the name of a TV that holds the priorities for some or all documents. If it doesn't exist or is empty, the priority is calculated as it is now.
