### ISSUE TITLE
Using allowedtemplates parameter doesnt output anything but a homepage link.

### ISSUE THREAD

**Issue by zaigham** [splittingred/GoogleSiteMap#6]
I am having a problem. If I call it as simple as [[!GoogleSitemap]], everything shows up, which means it is working. But I need to include selective templates/resources in the sitemap, thus I created this:

[[!GoogleSitemap? &allowedtemplates=`3,5,2,15,21,7,8,9`]]

It only shows the homepage link, a single link in the sitemap and nothing else.

Any clues?
## Its on Revo 2.0.7

http://screencast.com/t/wIZP5JQup

It looks like as soon as I add something in the allowedtemplates, it stops working. 

Tried all sorts of combinations etc.

**Comment by jeffwhitfield** [comment]
I've confirmed this to be an issue as well. I've experimented with this and it seems that it doesn't like certain templates for some reason.  Quite inconsistent.

**Comment by 01iv3r** [comment]
If I pass any paramaters to GoogleSiteMap in the snippet call, it breaks. the output is null.

setting paramaters with a property set works just fine, but then i don't believe it's possible to embed other snippets and output filters, for example `&excludeResources=`[[!GetIds? &ids=`c12`]]``

**Comment by splittingred** [comment]
This works fine for me in latest. Check again in 1.3.0, coming today.

**Comment by jeffwhitfield** [comment]
Cool!  Thanks for looking into it, Shaun.  Will look at 1.3.0 soon.  :)

Jeff
