### ISSUE TITLE
Sitemap not showing/rendering in IE7/8/9

### ISSUE THREAD

**Issue by MrReaL** [splittingred/GoogleSiteMap#8]
By adjusting the gtv.js 

,isArray: function(v) {
            return toString.apply(v) === '[object Array]';
        }

replaced with:

,isArray: function(v) {
            //check if v is an object as an array is an object
            if (typeof v == "object") 
            {
              //check the string value of the constructor for an array function
              var isArray = v.constructor.toString().match(/array/i);
              return ((isArray != null)?true:false);
            }
            //not an object so not an array
            return false;
            //toString.apply(v) === '[object Array]';
        }

**Comment by splittingred** [comment]
This is the wrong tracker. You're looking for the GoogleMapsTV tracker.
